name: Repository labels

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Upsert default labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: 'type: feature',  color: '1f883d', description: 'New feature' },
              { name: 'type: fix',      color: 'd73a4a', description: 'Bug fix' },
              { name: 'type: chore',    color: '6a737d', description: 'Maintenance tasks' },
              { name: 'type: refactor', color: 'fbca04', description: 'Refactoring' },
              { name: 'type: docs',     color: '0e8a16', description: 'Documentation' },
              { name: 'type: ci',       color: '5319e7', description: 'CI/CD' },
              { name: 'type: test',     color: 'a2eeef', description: 'Tests' },
            ];
            for (const label of labels) {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                });
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  new_name: label.name,
                  color: label.color,
                  description: label.description,
                });
              } catch (e) {
                if (e.status === 404) {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label.name,
                    color: label.color,
                    description: label.description,
                  });
                } else {
                  core.warning(`Failed to upsert label ${label.name}: ${e.message}`);
                }
              }
            }
