name: PR auto label

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Map PR type from title
        id: map
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title || '';
            const type = (title.match(/^(feat|fix|chore|refactor|docs|ci|test)(\(|:)/i) || [])[1];
            const mapping = {
              feat: 'type: feature',
              fix: 'type: fix',
              chore: 'type: chore',
              refactor: 'type: refactor',
              docs: 'type: docs',
              ci: 'type: ci',
              test: 'type: test',
            };
            const label = type ? mapping[type.toLowerCase()] : undefined;
            core.setOutput('label', label || '');
      - name: Apply label
        if: steps.map.outputs.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.map.outputs.label }}
